export const aiNewsSources = [
  {
    id: "huggingface-blog",
    name: "Hugging Face",
    type: "rss",
    url: "https://huggingface.co/blog/feed.xml",
    category: "AI 工具",
    enabled: true,
  },
  {
    id: "openai-news",
    name: "OpenAI",
    type: "rss",
    url: "https://openai.com/news/rss.xml",
    category: "AI 平台",
    enabled: true,
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind",
    type: "rss",
    url: "https://deepmind.google/blog/rss.xml",
    category: "研究論文",
    enabled: true,
  },
  {
    id: "brief-ai",
    name: "Brief AI",
    type: "html",
    parser: "brief-ai-archive",
    url: "https://ai.briefnewsletter.com/archive",
    category: "AI 電子報",
    language: "zh-Hant",
    maxItems: 3,
    enabled: true,
  },
  {
    id: "aibase-ai-daily",
    name: "AIBase AI 日報",
    type: "html",
    parser: "aibase-daily",
    url: "https://news.aibase.com/tw/daily",
    category: "AI 日報",
    language: "zh-Hant",
    maxItems: 3,
    enabled: true,
  },
  {
    id: "anthropic-news",
    name: "Anthropic",
    type: "rss",
    url: "https://www.anthropic.com/news/rss.xml",
    category: "AI 平台",
    // Anthropic 官方新聞頁目前未確認可用 RSS，先停用。未來可改用官方頁面抓取或可用 RSS 來源。
    enabled: false,
  },
];
