export type SiteLanguage = "zh-Hant" | "en" | "ja";

type Translation = Partial<Record<Exclude<SiteLanguage, "zh-Hant">, string>>;

const translations: Record<string, Translation> = {
  "重啟實驗室": { en: "Restart Lab", ja: "リスタートラボ" },
  "首頁": { en: "Home", ja: "ホーム" },
  "關於我": { en: "About", ja: "プロフィール" },
  "工具": { en: "Tools", ja: "ツール" },
  "文章": { en: "Articles", ja: "記事" },
  "購買清單": { en: "Buying List", ja: "購入リスト" },
  "聯絡我": { en: "Contact", ja: "お問い合わせ" },
  "AI 情報中心": { en: "AI News Center", ja: "AI情報センター" },
  "會員登入": { en: "Member Login", ja: "会員ログイン" },
  "下載": { en: "Downloads", ja: "ダウンロード" },
  "管理系統": { en: "Admin System", ja: "管理システム" },
  "網站總選單": { en: "Site Menu", ja: "サイトメニュー" },
  "先選大分類，再進小頁面": { en: "Choose a category, then open a page", ja: "カテゴリを選んでページへ進みます" },
  "主要頁面": { en: "Main Pages", ja: "主要ページ" },
  "會員與管理": { en: "Members & Admin", ja: "会員と管理" },
  "用 AI，把人生重新開機。": { en: "Restart your life with AI.", ja: "AIで人生を再起動する。" },
  "認識我": { en: "About James", ja: "Jamesについて" },
  "看 AI 工具": { en: "Explore AI Tools", ja: "AIツールを見る" },
  "看工具": { en: "View Tools", ja: "ツールを見る" },
  "看文章": { en: "Read Articles", ja: "記事を見る" },
  "看 AI 情報": { en: "Read AI News", ja: "AI情報を見る" },
  "AI 工具": { en: "AI Tools", ja: "AIツール" },
  "學習文章": { en: "Learning Articles", ja: "学習記事" },
  "這裡分成四個清楚入口。": { en: "Four clear ways to explore.", ja: "4つの入口から探索できます。" },
  "從 14 年軍旅，到 AI 時代重新開始。": { en: "A new start in the AI era after 14 years of military service.", ja: "14年間の軍歴を経て、AI時代に再出発。" },
  "我是詹棋庭，可以叫我詹姆士（James）": { en: "I am James Chan.", ja: "ジェームズです。" },
  "我親手做出來的 AI 工具": { en: "AI tools I built and curated", ja: "自分で作り、厳選したAIツール" },
  "AI 學習文章與實作筆記": { en: "AI learning articles and build notes", ja: "AI学習記事と実践ノート" },
  "AI 筆電購買清單": { en: "AI Laptop Buying List", ja: "AIノートPC購入リスト" },
  "下載中心": { en: "Download Center", ja: "ダウンロードセンター" },
  "會員中心": { en: "Member Center", ja: "会員センター" },
  "內容管理系統 MVP": { en: "Content Management System MVP", ja: "コンテンツ管理システム MVP" },
  "AI 小幫手": { en: "AI Assistant", ja: "AIアシスタント" },
  "AI 客服小幫手": { en: "AI Support Assistant", ja: "AIサポートアシスタント" },
  "你好！有什麼需要幫忙的嗎？": { en: "Hi! How can I help?", ja: "こんにちは！何をお手伝いできますか？" },
  "問我：James 的 AI 工具、文章、情報或聯絡方式": { en: "Ask about James's AI tools, articles, news, or contact details", ja: "AIツール、記事、情報、連絡先について質問してください" },
  "送出": { en: "Send", ja: "送信" },
  "常見問題": { en: "FAQ", ja: "よくある質問" },
  "AI 新手入門": { en: "AI for Beginners", ja: "AI入門" },
  "推薦 AI 工具": { en: "Recommend AI Tools", ja: "AIツール推薦" },
  "AI 教學文章": { en: "AI Tutorials", ja: "AI記事" },
  "聯絡 James": { en: "Contact James", ja: "Jamesに連絡" },
  "返回首頁": { en: "Back Home", ja: "ホームへ戻る" },
  "閱讀全文": { en: "Read more", ja: "全文を読む" },
  "來源": { en: "Source", ja: "出典" },
  "摘要": { en: "Summary", ja: "要約" },
  "AI 商城": { en: "AI Marketplace", ja: "AIマーケットプレイス" },
  "暫未開放": { en: "Not available yet", ja: "準備中" },
  "註冊帳號": { en: "Create an account", ja: "アカウント登録" },
  "Email": { en: "Email", ja: "メールアドレス" },
  "密碼": { en: "Password", ja: "パスワード" },
  "確認密碼": { en: "Confirm password", ja: "パスワードを確認" },
  "申請會員帳號": { en: "Apply for membership", ja: "会員登録を申請" },
  "待驗證會員": { en: "Pending verification", ja: "認証待ち会員" },
  "已驗證會員": { en: "Verified member", ja: "認証済み会員" },
  "6 位數驗證碼": { en: "6-digit verification code", ja: "6桁の認証コード" },
  "驗證帳號（測試模式）": { en: "Verify account (test mode)", ja: "アカウントを認証（テストモード）" },
  "目前點數": { en: "Current points", ja: "現在のポイント" },
  "每日簽到": { en: "Daily check-in", ja: "毎日のチェックイン" },
  "每週加點": { en: "Weekly bonus", ja: "毎週ボーナス" },
  "今天已簽到": { en: "Checked in today", ja: "本日はチェックイン済み" },
  "今天尚未簽到": { en: "Not checked in today", ja: "本日は未チェックイン" },
  "今日已簽到": { en: "Checked in today", ja: "本日はチェックイン済み" },
  "每日簽到 +10": { en: "Daily check-in +10", ja: "毎日チェックイン +10" },
  "本週已領取": { en: "Claimed this week", ja: "今週は受取済み" },
  "本週尚未領取": { en: "Not claimed this week", ja: "今週は未受取" },
  "本週已加點": { en: "Weekly bonus claimed", ja: "今週のボーナス受取済み" },
  "每週加點 +30": { en: "Weekly bonus +30", ja: "毎週ボーナス +30" },
  "點數紀錄": { en: "Point history", ja: "ポイント履歴" },
  "可兌換商品": { en: "Redeemable items", ja: "交換可能な商品" },
  "商品待研究": { en: "Rewards under research", ja: "交換商品を検討中" },
  "會員可瀏覽": { en: "Member browsing", ja: "会員が閲覧できる内容" },
  "查看 AI 情報": { en: "View AI News", ja: "AI情報を見る" },
  "前往會員中心": { en: "Open Member Center", ja: "会員センターへ" },
  "管理後台為管理員專用": { en: "The admin dashboard is for administrators only", ja: "管理ダッシュボードは管理者専用です" },
  "AI 情報管理為管理員專用": { en: "AI news management is for administrators only", ja: "AI情報管理は管理者専用です" },
  "目前尚未啟用正式管理員帳號與角色驗證。為避免一般會員取得 CMS、AI 情報新增、編輯或刪除權限，這個入口目前只顯示安全提示。": { en: "Administrator accounts and role checks are not enabled yet. To prevent members from receiving CMS or AI news create, edit, and delete access, this entry only shows a safe notice.", ja: "正式な管理者アカウントとロール認証は未実装です。会員にCMSやAI情報の追加・編集・削除権限を与えないため、この入口は安全な案内のみを表示します。" },
  "一般會員可以使用 AI 情報、工具、文章與會員點數 MVP；管理功能將在正式登入與角色權限完成後開放。": { en: "Members can use AI news, tools, articles, and the points MVP. Admin features will open after real authentication and role checks are complete.", ja: "会員はAI情報、ツール、記事、ポイントMVPを利用できます。管理機能は正式なログインとロール権限の完成後に公開します。" },
  "正式會員需要完成 Email 驗證後才會啟用。現在是前端測試模式，不會寄信、不會建立正式帳號，也不提供後台、商城或下載解鎖權限。": { en: "Full membership activates after email verification. This is front-end test mode: no email is sent, no real account is created, and no admin, marketplace, or download unlock is granted.", ja: "正式会員はメール認証後に有効になります。現在はフロントエンドのテストモードで、メール送信・正式アカウント作成・管理画面／購入／ダウンロード解除は行いません。" },
  "先申請會員帳號；密碼只在本次表單驗證使用，不會儲存在瀏覽器。": { en: "Apply for membership first. Your password is only validated in this form and is not stored in the browser.", ja: "先に会員登録を申請してください。パスワードはこのフォームで確認するだけで、ブラウザには保存されません。" },
  "已寄出 6 位數驗證碼到信箱。信箱驗證功能建置中，請以測試模式完成流程預覽。": { en: "A 6-digit code has been sent. Email delivery is under construction, so use test mode to preview the flow.", ja: "6桁のコードを送信しました。メール送信は開発中のため、テストモードで流れを確認してください。" },
  "這是測試模式會員狀態，不代表完成正式 Email 驗證，也不會開放管理後台、付費商品或下載內容。": { en: "This is a test-mode member state. It is not real email verification and does not unlock admin, paid products, or downloads.", ja: "これはテストモードの会員状態です。正式なメール認証ではなく、管理画面、有料商品、ダウンロードは解除されません。" },
  "點數 MVP 僅儲存在這台裝置，不可兌現或轉移。": { en: "The points MVP is stored only on this device and cannot be redeemed or transferred.", ja: "ポイントMVPはこの端末にのみ保存され、交換や譲渡はできません。" },
  "尚無點數紀錄。完成驗證後可以每日簽到與每週加點。": { en: "No point records yet. After verification, you can claim daily and weekly points.", ja: "ポイント履歴はまだありません。認証後、毎日・毎週ポイントを受け取れます。" },
  "商品待研究。目前不提供實體商品、物流、金流或點數兌換。": { en: "Rewards are under research. Physical goods, shipping, payments, and point redemption are not available yet.", ja: "交換商品は検討中です。実物商品、配送、決済、ポイント交換は未実装です。" },
  "一般會員可查看公開內容；AI 情報、工具與文章不需要付費解鎖。": { en: "Members can browse public content. AI news, tools, and articles do not require paid unlocks.", ja: "会員は公開コンテンツを閲覧できます。AI情報、ツール、記事は有料解除不要です。" },
};

export function translateSiteText(text: string, language: SiteLanguage) {
  if (language === "zh-Hant") return text;
  return translations[text]?.[language] ?? text;
}
